//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAI_UNAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class catMateriaTemaPregunta
    {
        public Nullable<int> TipoPreguntaID { get; set; }
        public string MateriaTemaPregunta { get; set; }
        public Nullable<int> MateriaTemaID { get; set; }
        public int MateriaTemaPreguntaID { get; set; }
    }
}
