//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAI_UNAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class catMateriaTemaPreguntaRespuesta
    {
        public string MateriaTemaPreguntaRespuesta { get; set; }
        public Nullable<bool> Respuesta { get; set; }
        public Nullable<int> MateriaTemaPreguntaID { get; set; }
        public string Justificacion { get; set; }
        public int MateriaTemaPreguntaRespuestaID { get; set; }
    }
}
