//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAI_UNAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inf_usuario()
        {
            this.inf_usr_personales = new HashSet<inf_usr_personales>();
            this.inf_usr_rh = new HashSet<inf_usr_rh>();
        }
    
        public System.Guid usuario_ID { get; set; }
        public Nullable<int> est_usr_ID { get; set; }
        public string cod_usr { get; set; }
        public string usr { get; set; }
        public string clave { get; set; }
        public string correo_corp { get; set; }
        public System.Guid centro_ID { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_usr_personales> inf_usr_personales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_usr_rh> inf_usr_rh { get; set; }
    }
}
