//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAI_UNAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAreasPerfil
    {
        public int AreaID { get; set; }
        public int PerfilID { get; set; }
        public int AreasPerfilID { get; set; }
    
        public virtual catAreas catAreas { get; set; }
        public virtual catPerfiles catPerfiles { get; set; }
    }
}
