//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAI_UNAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContactoProveedores
    {
        public System.Guid ContactoProveedorID { get; set; }
        public string Nombre { get; set; }
        public string email { get; set; }
        public string Telefono { get; set; }
        public string CalleNumero { get; set; }
        public string CodigoPostal { get; set; }
        public Nullable<int> ColoniaID { get; set; }
        public Nullable<int> EstatusRegistroID { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public System.Guid ProveedorID { get; set; }
    
        public virtual tblProveedores tblProveedores { get; set; }
    }
}
