//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAI_UNAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductos
    {
        public System.Guid ProductoID { get; set; }
        public string CodigoProducto { get; set; }
        public int ProductosCategoriaID { get; set; }
        public string Descripcion { get; set; }
        public string Caracteristica { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<int> EstatusRegistroID { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual tblProductosCategoria tblProductosCategoria { get; set; }
    }
}
