//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAI_UNAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsuariosCentros
    {
        public System.Guid UsuarioID { get; set; }
        public int TipoUsuarioID { get; set; }
        public int PerfilID { get; set; }
        public string CodigoUsuario { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public int GeneroID { get; set; }
        public string CorreoPersonal { get; set; }
        public string CorreoTrabajo { get; set; }
        public string Celular { get; set; }
        public int UbicacionID { get; set; }
        public int EstatusRegistroID { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.Guid CentroID { get; set; }
    
        public virtual tblCentro tblCentro { get; set; }
    }
}
